spring.application.name: notificationService
server.port: 8410
spring:
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: notification-service-group
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            properties:
                spring.json.trusted.packages: "*"
            auto-offset-reset: earliest

        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                enable.idempotence: true
                acks: all


eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

kafka:
    topic:
        bookings: bookings-topic
